name:                metahs
version:             0.1.0.0
github:           "https://SaKa1979@bitbucket.org/SaKa1979/metahs"
license:             BSD3
author:              "Henrie Vos, Sander Kamps"
maintainer:          "sanderkamps79@gmail.com"
copyright:           "2018 Sander Kamps"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on bitbucket at https://bitbucket.org/SaKa1979/metahs/src/master/README

dependencies:
- base >= 4.7 && < 5
- containers
- pretty
- graphviz
- fgl
- blaze-html
- haskell-src-exts
- directory
- filepath
- syb
- split
- text
- time

library:
  source-dirs: src