name:                metahs
version:             0.0.1
github:              "https://SaKa1979@bitbucket.org/SaKa1979/metahs"
license:             MIT
author:              "Henrie Vos, Sander Kamps"
maintainer:          "sanderkamps79@gmail.com"
copyright:           "2019 Sander Kamps"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on bitbucket at https://bitbucket.org/SaKa1979/metahs/src/master/README

dependencies:
- base >= 4.7 && < 5
- containers
- pretty
- graphviz
- filepath
- fgl
- haskell-src-exts
- directory
- syb
- split
- text

library:
  source-dirs: src

tests:
  test-metahs:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -main-is Spec
    dependencies:
      - HUnit
      - metahs